name: national_generation_capacity

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.5
  - bokeh=0.12.2  # used in tests.ipynb
  - notebook  # jupyter notebook
  - numpy=1.11.1
  - openpyxl  # pandas: excel i/o
  - pandas=0.18.1
  - pyyaml=3.12
  - xlrd  # pandas: excel i/o
  - xlsxwriter
